[package]
name = "numerics"
version = "0.1.0"
authors = ["dineshadepu <adepu.dinesh.a@gmail.com>"]
edition = "2018"

[lib]
name = "numerics"
crate-type = ["cdylib"]

[dependencies]
numpy = "*"
ndarray = "0.12"

[dependencies.pyo3]
version = "0.8"
features = ["extension-module"]
